cities=["a","b","c"]
for city in cities:
    print(city)
print(123)

In [4]:
i=0
while i<3:
    i+=1
    print(i)

1
2
3


In [5]:
for i in range(15):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [7]:
cities=[["a","b","c"],["d","e","f"]]
for i in cities:
    for j in i:
        print(j)

a
b
c
d
e
f


In [10]:
students=["tom","jim","ann","sue"]
scores=[70,80,85,75]
indexes=[0,1,2,3]
name="sue"
score=0
for i in indexes:
    if students[i]==name:
        score=scores[i]
print(score)

75


In [12]:
scores={}
print(type(scores))
scores["jim"]=80
scores["sue"]=85
print(scores)
print(scores["jim"])

<class 'dict'>
{'jim': 80, 'sue': 85}
80


In [18]:
students={
    "tom":60,
    "jim":70
}
print(students["jim"])

70


In [22]:
pantry=["fa","fb","fc","fc","fd","fd","fd"]
pantry_c={}
for i in pantry:
    if i in pantry_c:
        pantry_c[i]+=1
    else: 
        pantry_c[i]=1
print(pantry_c)

{'fa': 1, 'fb': 1, 'fc': 2, 'fd': 3}


In [30]:
import numpy
w_a=numpy.genfromtxt("C:\\Users\\hzg0601\\Desktop\\world_alcohol.txt",delimiter=",",dtype=str,skip_header=1)
print(type(w_a))
print(w_a)



<class 'numpy.ndarray'>
[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ..., 
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [31]:
import numpy as np
print(np.arange(15))
a=np.arange(15).reshape(3,5)
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
a.shape

(3, 5)

In [33]:
a.ndim

2

In [34]:
a.dtype.name

'int32'

In [35]:
a.size

15

In [36]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [38]:
np.ones((2,3,4),dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [39]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [40]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
np.random.random((2,3))*2-1#0~1

array([[-0.53997859, -0.54897707,  0.89035827],
       [-0.99747839,  0.78170367,  0.25879692]])

In [43]:
from numpy import pi
np.linspace(0,2*pi,100)

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [48]:
#np.sin(np.)
a=np.array([20,30,40,50]).reshape(2,2)
b=np.arange(4).reshape(2,2)
a-b
print(a.dot(b))
print(np.dot(a,b))
print(a*b)#对应相乘

[[ 60 110]
 [100 190]]
[[ 60 110]
 [100 190]]
[[  0  30]
 [ 80 150]]


In [3]:
import numpy as np
print(help(np.genfromtxt))

Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Mote
        that generators must return byte strings in Python 3k.  The strings
        in a list or produced by a 

In [4]:
vector=np.array([1,2,3,4])
vector==10

array([False, False, False, False], dtype=bool)

In [5]:
print(np.exp(vector))

[  2.71828183   7.3890561   20.08553692  54.59815003]


In [6]:
print(np.sqrt(vector))

[ 1.          1.41421356  1.73205081  2.        ]


In [11]:
a=np.floor(10*np.random.random((3,4)))
a.reshape(2,6)

array([[ 1.,  9.,  3.,  5.,  9.,  4.],
       [ 3.,  7.,  3.,  5.,  4.,  9.]])

In [17]:
b=np.random.random((3,4))

In [19]:
print(np.vstack((a,b)))

[[ 1.          9.          3.          5.        ]
 [ 9.          4.          3.          7.        ]
 [ 3.          5.          4.          9.        ]
 [ 0.34174164  0.85257082  0.01673457  0.45431449]
 [ 0.97014968  0.07713323  0.1028344   0.7373009 ]
 [ 0.26781977  0.8403667   0.77823671  0.11531906]]


In [20]:
print(np.vsplit(a,3))

[array([[ 1.,  9.,  3.,  5.]]), array([[ 9.,  4.,  3.,  7.]]), array([[ 3.,  5.,  4.,  9.]])]


In [21]:
print(a)

[[ 1.  9.  3.  5.]
 [ 9.  4.  3.  7.]
 [ 3.  5.  4.  9.]]


In [25]:
print(np.hsplit(a,(2,3)))

[array([[ 1.,  9.],
       [ 9.,  4.],
       [ 3.,  5.]]), array([[ 3.],
       [ 3.],
       [ 4.]]), array([[ 5.],
       [ 7.],
       [ 9.]])]


In [26]:
print(a is b)

False


In [27]:
b.shape=4,3

In [28]:
print(id(a))

1677354362320


In [30]:
c=a.copy()

In [3]:
import numpy as np
data=np.sin(np.arange(20).reshape(5,4))
print(data)
ind=data.argmax(axis=0)#0按列
print(ind)
data_max=data[ind,range(data.shape[1])]
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[ 0.98935825  0.84147098  0.99060736  0.6569866 ]


In [22]:
a=np.arange(0,40,10)#按列排
print(a)
print(a.shape)
b=np.tile(a,(3,5))#复制
print(b)

[ 0 10 20 30]
(4,)
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]


In [24]:
print(np.sort(a,axis=0))#按列
range(data.shape[1])
print(np.argsort(a))

[ 0 10 20 30]
[0 1 2 3]


In [65]:
import pandas as ps
fs=ps.read_csv("C:\\Users\\hzg0601\\Desktop\\books\\food_info.csv")
fs.dtypes#数据框，object字符类型
#help(ps.read_csv)
#fs.head()
fs.head(3)
fs.tail(3)
fs.columns
fs.shape
#fs.loc[4:6]
#fs.loc[[2,3,4]]
fs[["NDB_No","Zinc_(mg)"]]

####################################################################
cn=fs.columns.tolist()
gram_c=[]
for c in cn:
    if c.endswith("(g)"):
        gram_c.append(c)#添加
grd=fs[gram_c]
print(grd.shape)
grdq=grd.loc[2]
grdt=(grd/1000-10)*2
fsn=fs.copy()
#fs["nw"]=grdt
fsn["nw"]=grdq
grdq.max

(8618, 10)


<bound method Series.max of Water_(g)          0.240
Protein_(g)        0.280
Lipid_Tot_(g)     99.480
Ash_(g)            0.000
Carbohydrt_(g)     0.000
Fiber_TD_(g)       0.000
Sugar_Tot_(g)      0.000
FA_Sat_(g)        61.924
FA_Mono_(g)       28.732
FA_Poly_(g)        3.694
Name: 2, dtype: float64>

In [71]:
fs.sort_values("Sodium_(mg)",inplace=1,ascending=0)#默认从小到大

In [105]:
import pandas as pd
import numpy as np
ts=pd.read_csv("C:\\Users\\hzg0601\\Desktop\\books\\titanic_train.csv")
#ts.head
age=ts["Age"]
age_is_null=pd.isnull(age)
print(age_is_null)
ant=age[age_is_null]
age_nc=len(ant)
print(age_nc)
cma=ts["Age"][age_is_null==0]
scma=ts["Age"].mean
pa_cl=[1,2,3]
f_b_c={}
for i in pa_cl:
    pc_r=ts[ts["Pclass"]==i]
    pc_f=pc_r["Fare"]
    f_f_c=pc_f.mean()
    f_b_c[i]=f_f_c
#print(f_b_c)

0      False
1      False
2      False
3      False
4      False
5       True
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17      True
18     False
19      True
20     False
21     False
22     False
23     False
24     False
25     False
26      True
27     False
28      True
29      True
       ...  
861    False
862    False
863     True
864    False
865    False
866    False
867    False
868     True
869    False
870    False
871    False
872    False
873    False
874    False
875    False
876    False
877    False
878     True
879    False
880    False
881    False
882    False
883    False
884    False
885    False
886    False
887    False
888     True
889    False
890    False
Name: Age, dtype: bool
177


In [86]:
pa_su=ts.pivot_table(index="Pclass",values="Survived",aggfunc=np.mean)#数据投石表
pa_a=ts.pivot_table(index="Pclass",values="Age")#默认函数为均值
po_st=ts.pivot_table(index="Embarked",values=["Fare","Survived"],aggfunc=np.sum)
dropts=ts.dropna(axis=1)#0是列，1是行
ri83a=ts.loc[83,"Age"]
nts=ts.sort_values("Age",ascending=0)
tsre=nts.reset_index(drop=1)#从新编索引
##.apply传递函数

def not_null_count(column):
    column_null=pd.isnull(column)
    null=column[column_null]
    return len(null)
column_null_count=ts.apply(not_null_count)
#print(column_null_count)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [107]:
#######################Series#############################
fandango=pd.read_csv("C:\\Users\\hzg0601\\Desktop\\fandango_score_comparison.csv")
series_film=fandango["FILM"]
series_rt=fandango["RottenTomatoes"]
from pandas import Series
film_names=series_film.values
rt_scores=series_rt.values
se_cu=Series(rt_scores,index=film_names)
#se_cu[["Minions (2015)","Leviathan (2014)"]]
#se_cu[5:10]

In [97]:
or_in=se_cu.index.tolist()
sin=sorted(or_in)
s_b_i=se_cu.reindex(sin)

In [106]:
#se_cu.sort_index()
#se_cu.sort_values()


In [104]:
#print(np.add(se_cu,se_cu))#求和
np.sin(se_cu)
np.max(se_cu)

100

In [109]:
#sss=se_cu>50
#ssb=se_cu<70
#sss&ssb


In [110]:
fandango_films=fandango.set_index("FILM",drop=0)
fandango_films["Minions (2015)":"Hot TUb Time Machine 2 (2015)"]
fandango_films.loc["Minions (2015)":"Hot TUb Time Machine 2 (2015)"]#按字母索引

In [ ]:
#lambda x:np.std(xxx)